stages:
  - build
  - staging
  - deploy

build:
  stage: build
  image: google/cloud-sdk:latest

  script:
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud builds submit --tag $IMAGE_NAME:latest --gcs-log-dir gs://spur-data/logs/builds/
  only:
    - master
    - dev
  except:
    - tags
    - schedules

staging:
  stage: staging
  image: google/cloud-sdk:latest

  script:
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud run deploy staging-spur-enrichment-for-maltego --image $IMAGE_NAME:latest --platform managed --region=us-east1
  only:
    - dev
  except:
    - tags
    - schedules

deploy:
  stage: deploy
  image: google/cloud-sdk:latest

  script:
    - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - gcloud run deploy spur-enrichment-for-maltego --image $IMAGE_NAME:latest --platform managed --region=us-east1
  only:
    - master
  except:
    - tags
    - schedules

